<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-03T14:00:21 GMT-04:00" name="Failed suite [Suite]" finished-at="2022-05-03T14:00:22 GMT-04:00" duration-ms="1108">
    <groups>
    </groups>
    <test started-at="2022-05-03T14:00:21 GMT-04:00" name="Test(failed)" finished-at="2022-05-03T14:00:22 GMT-04:00" duration-ms="1108">
      <class name="testclasses.TestingTest">
        <test-method signature="test1Test()[pri:0, instance:testclasses.TestingTest@5e0826e7]" started-at="2022-05-03T14:00:21 GMT-04:00" name="test1Test" finished-at="2022-05-03T14:00:22 GMT-04:00" duration-ms="1026" status="FAIL">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method testclasses.TestingTest.test1Test() didn't finish within the time-out 1000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testclasses.TestingTest.test1Test() didn't finish within the time-out 1000
at java.base@17/java.lang.Thread.sleep(Native Method)
at app//testclasses.TestingTest.test1Test(TestingTest.java:12)
at java.base@17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:44)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:72)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:10)
at java.base@17/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1Test -->
      </class> <!-- testclasses.TestingTest -->
    </test> <!-- Test(failed) -->
  </suite> <!-- Failed suite [Suite] -->
</testng-results>
